### ISSUE TITLE
About the SNV between human and chimp genome

### ISSUE THREAD

**Issue by WeiCSong** [TheFraserLab/Agoglia_HumanChimpanzee2020#1]
Hi, Congratulation on the great work! I noticed that you have generated a list of genome-wide SNV between human and chimp, and I wonder whether you have saved this file (including non-coding SNV) and whether it could be shared. If it was not saved, could you share the code for the hg38-pantro4 alignment? Thank you very much for your help!

**Comment by rmagoglia** [comment]
Hi WeiCSong,

Thanks for your inquiry, and apologies for the delay. The list of SNPs used in our study is available upon request (too large to upload here directly), with coordinates for either the human (Hg38) or chimpanzee (PanTro5) genomes. We used our RNA-seq data to validate the SNPs, so the majority of these will be located in coding exons. If you're interested in any updates or more recent lists generated in the lab, I recommend contacting the corresponding author from the manuscript, Hunter Fraser (hbfraser@stanford.edu).
